name: release binary

on:
  push:
    tags:
      - v*.*.*
    branches:
      - master

jobs:
  build-client:
    name: Build-Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install, and build
        run: |
          cd client
          yarn install
          yarn build:stage 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: client
          path: client/dist

  build-server:
    name: Build-server
    runs-on: ubuntu-latest
    needs: build-client
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Download Client artifact
      uses: actions/download-artifact@v1
      with:
        name: client
        path: client/dist
    - name: Get dependencies
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
      run: |
        go get github.com/rakyll/statik
        cd server
        $GOPATH/bin/statik --src ../client/dist
    - name: Build
      run: |
        cd server
        go build -v .
    - name: Test
      run: |
        cd server
        go test
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: server/main

